### ISSUE TITLE
Request: add schemaUpdateOptions to to_gbq()

### ISSUE THREAD

**Issue by yiga2** [googleapis/python-bigquery-pandas#107]
Useful if table already exists but `df` has more columns e.g. appending to historical data with 'old' schema.

Note that currently the (Python) Client library does not support that property - as per 0.29.

Workaround is `LoadJobConfig._properties.__setitem__('schemaUpdateOptions', ['ALLOW_FIELD_ADDITION'])`.

**Comment by tswast** [comment]
Now that `to_gbq` is creating load jobs, it would be good to allow passing in a whole job config dictionary in the way that `read_gbq` does with it’s `configuration` argument.

**Comment by tswast** [comment]
Closing in favor of https://github.com/googleapis/python-bigquery-pandas/issues/425
