### ISSUE TITLE
ENH: Read BigQuery query table without a query

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery-pandas#266]
It can cost a lot to run a `SELECT * FROM my_table` query, and yet from an API perspective, this query is completely unnecessary, as one can list the rows from the table directly for free with `tabledata.list`. I propose

```
df = pandas_gbq.read_gbq("my-project.my_dataset.my_table")
```

which will download a table directly (using `bigquery_client.list_rows().to_dataframe()`). Since all queries must contain some kind of whitespace and table IDs cannot contain any whitespace, we can use that to disambiguate query versus table ID.

**Comment by max-sixty** [comment]
I didn't know about that - I had thought you could run a preview, but not download a whole table that way.

Not opposed to it. I'm not sure it's _that_ helpful given than a large enough table to be expensive to query is also impractical to download over JSON into memory. 
But that's not an argument to not have the functionality, am +0 !

**Comment by tswast** [comment]
I think this feature would help with testing https://github.com/googleapis/python-bigquery-pandas/issues/365, as I realized I'm using the `google-cloud-bigquery` `bigquery_client.list_rows(table_id).to_dataframe(...)` pattern in https://github.com/googleapis/python-bigquery-pandas/pull/442 which doesn't actually test the full round trip via pandas-gbq.
