### ISSUE TITLE
ENH: Use Fletcher to better support strings, structs, and arrays

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery-pandas#274]
I recently learned about [Fletcher](https://fletcher.readthedocs.io/en/latest/), which provides a pandas extension dtype that is backed by pyarrow.

Since it's backed by arrow, it avoids having to use the object dtype for strings, structs, and arrays. But also, since it's only 0.1, this should probably be opt-in.

Similar to https://github.com/pydata/pandas-gbq/issues/242, since both these proposals use extension dtypes.

**Comment by meredithslota** [comment]
The project was archived earlier this year and is no longer supported (https://github.com/xhochy/fletcher/tree/master) — closing.

**Comment by tswast** [comment]
Indeed. ArrowDtype is now built-in to Pandas. https://github.com/googleapis/python-bigquery-pandas/issues/621 tracks a way to integrate with ArrowDtype in a way consistent with other pandas I/O methods.
