### ISSUE TITLE
AttributeError: module 'pandas.compat' has no attribute 'PY3' and InvalidPrivateKeyFormat

### ISSUE THREAD

**Issue by alyssafriesen** [googleapis/python-bigquery-pandas#283]
When running a python app on Google App Engine I am getting the following error:

     AttributeError: module 'pandas.compat' has no attribute 'PY3' at
          get_service_account_credentials (/env/lib/python3.7/site-packages/pandas_gbq/auth.py:75)

This is occurring at the same time as this error:

> pandas_gbq.exceptions.InvalidPrivateKeyFormat: Detected private_key as path. Private key is missing or invalid. It should be service account private key JSON (file path or string contents) with at least two keys: "client_email" and "private_key". Can be obtained from: https://console.developers.google.com/permissions/serviceaccounts
>   at get_service_account_credentials (/env/lib/python3.7/site-packages/pandas_gbq/auth.py:91)
>   at get_credentials (/env/lib/python3.7/site-packages/pandas_gbq/auth.py:41)
>   at __init__ (/env/lib/python3.7/site-packages/pandas_gbq/gbq.py:345)
>   at to_gbq (/env/lib/python3.7/site-packages/pandas_gbq/gbq.py:1104)
>   at to_gbq (/env/lib/python3.7/site-packages/pandas/io/gbq.py:209)
>   at to_gbq (/env/lib/python3.7/site-packages/pandas/core/frame.py:1503)
>   at bigquery_load (/srv/etl_process/methods/methods.py:45)
>   at main (/srv/etl_process/run_facebookads.py:257)
>   at run (/srv/etl_process/run_facebookads.py:265)
>   at facebook_ads (/srv/main.py:22)
>   at dispatch_request (/env/lib/python3.7/site-packages/flask/app.py:1799)
>   at full_dispatch_request (/env/lib/python3.7/site-packages/flask/app.py:1813)
>   at reraise (/env/lib/python3.7/site-packages/flask/_compat.py:35)
>   at handle_user_exception (/env/lib/python3.7/site-packages/flask/app.py:1718)
>   at full_dispatch_request (/env/lib/python3.7/site-packages/flask/app.py:1815)
>   at wsgi_app (/env/lib/python3.7/site-packages/flask/app.py:2292)

I can't tell which error is impacting the other, but it seems like they must be related if they are occurring simultaneously, right? My .json file is valid and hasn't been changed since getting it from Google. I have doublechecked the path as well.

**Comment by tswast** [comment]
Thanks for the report, @alyssafriesen. What versions of the following are you using?

- pandas-gbq
- pandas
- Python
- App Engine

`pandas.compat.PY3` was removed from the pandas package in pandas 0.25.0.

**Comment by alyssafriesen** [comment]
I believe I am using the most recent version of pandas-gbq and pandas (as I am not calling a specific version in the requirements file). I am on Python 3.7 and App Engine Standard on a B8 instance class.

**Comment by mycaule** [comment]
Hi @alyssafriesen how did you solve your problem?

**Comment by max-sixty** [comment]
If anyone is seeing this, please follow up with the list from @tswast

**Comment by meredithslota** [comment]
Since pandas 0.24.2 was the last version to support Python 2 — and we now require Python 3.7+ — instead of adding support for this, we'd likely just bump the min version of pandas required to 0.25.0 (which dropped `pandas.compat.PY3` anyway).
