### ISSUE TITLE
TST: Migrate to conda `venv_backend` for conda tests on CI

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery-pandas#288]
The latest version of nox includes https://github.com/theacodes/nox/pull/217, which adds a `venv_backend='conda'` option to create a conda environment instead of a virtualenv. It also adds a `conda_install` command, so that we can install packages via conda instead of pip.

We should migrate from the `run_conda.sh` script in our CI setup to using a conda test session in our noxfile.

**Comment by meredithslota** [comment]
Closing as "Obsolete" — we've moved off CircleCI, and are standardizing our testing across the different libraries.
