### ISSUE TITLE
Add MERGE functionality

### ISSUE THREAD

**Issue by ZiggerZZ** [googleapis/python-bigquery-pandas#323]
In BigQuery it is possible to _merge_ two tables:

```sql
MERGE DATASET.table T
USING (SELECT * FROM DATASET.another_table) S
ON T.id = S.id
WHEN MATCHED THEN
	UPDATE SET value = S.value
WHEN NOT MATCHED THEN
	INSERT ROW
```

Is it possible to add such functionality to DataFrame.to_gbq function? I.e. something like `df.to_gbq(if_exists='merge', on_a='id', on_b='id')`, or even provide a possibilty to write a whole ON clause `df.to_gbq(if_exists='merge', on='A.city = B.city AND A.date = B.date'`

**Comment by tswast** [comment]
To clarify, do you mean for this to be a sort of "upsert", which matches by primary key and replaces existing values?

**Comment by ZiggerZZ** [comment]
Yes, or, more generally, by any condition, i.e. `A.city = B.city AND A.date = B.date`.
And insert, if no match by primary key / condition.

**Comment by ZiggerZZ** [comment]
@tswast any news on this? Do you want me to have a look at this and open a PR?

**Comment by tswast** [comment]
I don't have time to work on it. I think it'd be best to nail down the design before opening a PR.

Besides `if_exists='merge'`, we need to account for large dataframes. Anything larger than the [BigQuery query length limit](https://cloud.google.com/bigquery/quotas#query_jobs) (currently 12 MB) will need to be either staged in a temporary table (or even GCS with use of external table feature) or split into multiple queries.

As the row size limit is currently 100 MB which is less than the query length limit, staging the data is required for the most general solution.

**Comment by ZiggerZZ** [comment]
I'm not yet familiar with pandas-gbq codebase, so it will take me a while.
In my projects, I split data into batches and merge them into the main using temporary tables. Can we just do like this? Here's the psedocode:

```python
# we want to merge `data` to `table_id` using `condition`
data_batches = split_data_into_batches(data)
for data_batch in data_batches:
    tmp_id = _id_generator()
    table_tmp_id = f"{table_id}_tmp_{tmp_id}"
    client.create_table(table=bigquery.Table(table_tmp_id, schema=table_id.schema)), expiration=1 hour)
    query = f"""MERGE `{table_id}` T
USING `{table_tmp_id}` S
ON {condition}
WHEN MATCHED THEN
	UPDATE SET ...
WHEN NOT MATCHED THEN
	INSERT ROW"""
    client.query(query).result()
```

**Comment by dsantiago** [comment]
Is this on watch? i think upsert will be a good improvement, for now i need to delete data and after do to_gbq with append mode.

**Comment by ZiggerZZ** [comment]
@dsantiago I built a lib that does this and has a couple other handy functionalities - https://pypi.org/project/pygbq/
Code quality could be better but it does the job

**Comment by dsantiago** [comment]
> @dsantiago I built a lib that does this and has a couple other handy functionalities - https://pypi.org/project/pygbq/
> Code quality could be better but it does the job

Good job, i will sure check it out!

**Comment by parthea** [comment]
@violetbrina , PRs are welcome!

**Comment by fanarat** [comment]
merge option would be awesome

**Comment by atapia238** [comment]
I'd love to have this option, too. We have a process to consolidate specific lines of data from different files we receive daily, but everything gets duplicated if we receive the same file twice for any reason. Our only solution is to remove everything in our BQ table that's related to that file and re-process it.

**Comment by pedrohml** [comment]
upvoting for MERGE option

**Comment by Linchin** [comment]
BigFrames' [`merge()` method](https://cloud.google.com/python/docs/reference/bigframes/latest/bigframes.dataframe.DataFrame#bigframes_dataframe_DataFrame_merge) might be exactly what you are looking for. It's essentially a remote BigQuery table that behaves like a dataframe. Here's their project: https://github.com/googleapis/python-bigquery-dataframes

I will close this issue for now, but feel free to leave more comments if you have any further questions or requirements.

**Comment by adrianbr** [comment]
For merge you can now use dlt's pipeline.run the same way as df.to_sql() except dlt is made for data loading and will do it robustly and with many options.
https://dlthub.com/docs/general-usage/incremental-loading
example:
```
load_info = pipeline.run(
    df,
    write_disposition="merge",
    primary_key="id",
    table_name="users"
)
```

**Comment by EugeneYushin** [comment]
> BigFrames' [`merge()` method](https://cloud.google.com/python/docs/reference/bigframes/latest/bigframes.dataframe.DataFrame#bigframes_dataframe_DataFrame_merge) might be exactly what you are looking for. It's essentially a remote BigQuery table that behaves like a dataframe. Here's their project: https://github.com/googleapis/python-bigquery-dataframes
> 
> I will close this issue for now, but feel free to leave more comments if you have any further questions or requirements.

`BigFrames.merge` (and respective pandas version) seems to be different to DB MERGE functionality. It gets merged dataframe back to you (in-memory), while DB merges final table with (let's call it) staging one. It looks that BigFrames version won't write any data back to Big Query table
