### ISSUE TITLE
Feature Request: Add retry functionality

### ISSUE THREAD

**Issue by uniocto** [googleapis/python-bigquery-pandas#358]
Sometimes, I get the following error.
```
internalError  500
rateLimitExceeded  403
```
https://cloud.google.com/bigquery/docs/error-messages?hl=ja

So, Is it possible to add functionality to `pandas-gbq` that allows retries depending on the error code?

**Comment by tswast** [comment]
This is a good feature request. I've been thinking about this in relation to https://github.com/googleapis/python-bigquery/issues/539 and I think pandas-gbq offers the right level of abstraction where this would be possible compared to the lower-level client library.

**Comment by tswast** [comment]
Fixed by https://github.com/googleapis/python-bigquery/pull/837

When `google-cloud-bigquery` 2.24.0 or later is installed, queries are retried automatically.
