### ISSUE TITLE
Import attribute error 

### ISSUE THREAD

**Issue by pj598** [googleapis/python-bigquery-pandas#363]
I've been getting an attribute error when I try to import pandas-gbq. 

> Traceback (most recent call last):
File "/Users/Desktop/temp.py", line 4, in <module>
    import pandas_gbq
 File "/Users/opt/anaconda3/lib/python3.8/site-packages/pandas_gbq/__init__.py", line 1, in <module>
    from .gbq import to_gbq, read_gbq, Context, context  # noqa
File "/Users/opt/anaconda3/lib/python3.8/site-packages/pandas_gbq/gbq.py", line 12, in <module>
    from google.cloud import bigquery
 File "/Users/opt/anaconda3/lib/python3.8/site-packages/google/cloud/bigquery/__init__.py", line 35, in <module>
    from google.cloud.bigquery.client import Client
File "/Users/opt/anaconda3/lib/python3.8/site-packages/google/cloud/bigquery/client.py", line 58, in <module>
    from google.cloud.bigquery import _pandas_helpers
File "/Users/opt/anaconda3/lib/python3.8/site-packages/google/cloud/bigquery/_pandas_helpers.py", line 40, in <module>
    from google.cloud.bigquery import schema
File "/Users/opt/anaconda3/lib/python3.8/site-packages/google/cloud/bigquery/schema.py", line 28, in <module>
    "STRING": types.StandardSqlDataType.STRING,
AttributeError: type object 'StandardSqlDataType' has no attribute 'STRING' 

I'm using Python 3.8 and updated any applicable packages. Tried using 3.7 and got the same error. Any ideas on how to solve this? Thanks!

**Comment by max-sixty** [comment]
What versions are you running on?

**Comment by pj598** [comment]
Slightly new to coding so let me know if I'm giving you the wrong info. 
pandas: 1.0.5
pandas-gbq: 0.15.0
pydata-google-auth: 1.2.0
google-auth: 1.30.0
google-auth-oauthlib: 0.4.4
google-cloud-bigquery: 2.15.0
google-cloud-bigquery-storage: 2.4.0

**Comment by max-sixty** [comment]
Are you sure you're on 2.15.0 for google-cloud-bigquery? I see slightly different code at that point: https://github.com/googleapis/python-bigquery/blob/v2.15.0/google/cloud/bigquery/schema.py#L28-L29

Though regardless, this looks like an error in that project, so it's probably better to post there — it looks like `from google.cloud import bigquery` breaks. Sorry not to be more helpful.

**Comment by pj598** [comment]
yeah, my computer is still saying its 2.15.0. Thank you for your help! I really appreciate it.

**Comment by tswast** [comment]
Not enough information to debug, so closing. For future reference you may want to try:

```
import google.cloud.bigquery

print(google.cloud.bigquery.__version__)
```

to check the package version. Sometimes the Python binary you're running is out-of-sync with what pip/conda says.

**Comment by Robotatron** [comment]
> Not enough information to debug, so closing. For future reference you may want to try:
> 
> ```
> import google.cloud.bigquery
> 
> print(google.cloud.bigquery.__version__)
> ```
> 
> to check the package version. Sometimes the Python binary you're running is out-of-sync with what pip/conda says.

Installed just now from google docs with `conda install -c conda-forge pandas-gbq google-cloud-bigquery`

![chrome_LmK2BxLqc7](https://user-images.githubusercontent.com/95919873/148206429-0170577a-75cb-487e-a753-41e69e3a0eef.png)
