### ISSUE TITLE
migration to googleapis org

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery-pandas#367]
I recently migrated https://github.com/googleapis/python-bigquery-sqlalchemy to the googleapis org, where I'm able to benefit from release tooling and issue triage.

Since I'm the primary maintainer here, it might make sense to do the same for pandas-gbq if there are no objections from the community.

**Edit** Now that the repository has been migrated, I'll keep this issue open to track all the changes needed:

- [x] Add repo metadata (https://github.com/googleapis/python-bigquery-pandas/pull/370)
- [x] Integrate with release-please
  - [x] Remove versioneer (https://github.com/googleapis/python-bigquery-pandas/pull/371)
  - [x] Migrate changelog to CHANGELOG.md (https://github.com/googleapis/python-bigquery-pandas/pull/372)
  - [x] Grant PyPI permissions to release bot
- [x] Use shared templates (owlbot / synthtool) for continuous integration and testing
  - [x] Enable owlbot and Kokoro https://github.com/googleapis/python-bigquery-pandas/pull/380
  - [x] Disable CircleCI -- Add conda session to noxfile and Kokoro jobs https://github.com/googleapis/python-bigquery-pandas/pull/638
- [x] Update docs to reflect new package location.
  - [x] Publish docs to https://googleapis.dev/python/pandas-gbq/latest
  - [x] Update README to point to new docs location
  - [x] Update contributing docs to reflect use of conventional commits messages https://github.com/googleapis/python-bigquery-pandas/pull/504/files
- [x] Add ROADMAP.md indicating the purpose of this package in relation to `google-cloud-bigquery` and `pandas` https://github.com/googleapis/python-bigquery-pandas/issues/149

**Comment by max-sixty** [comment]
Sounds good! Hope all's well @tswast !

**Comment by meredithslota** [comment]
All items are marked complete. I also sent https://github.com/googleapis/python-bigquery-pandas/pull/504/files to dedupe the main contributing guides.
