### ISSUE TITLE
Authenticate with Pandas GBQ for Python BigQuery client

### ISSUE THREAD

**Issue by ianhellstrom** [googleapis/python-bigquery-pandas#384]
I'm trying to list all the tables in a GCP project inside a Jupyter notebook. I can use the information schema tables, but then I have to know all the datasets in advance.

Instead, I can use the [Python client](https://cloud.google.com/bigquery/docs/listing-datasets), but that requires authentication. People who (re-)use the notebook do not have service account keys or local keys from the gcloud SDK, but they do authenticate with their own accounts using Pandas GBQ.

Is there a way I can pass that information on to Python client?

**Comment by tswast** [comment]
@ianhellstrom That's a great question! We anticipated this need and actually refactored the auth logic into a separate package called `pydata-google-auth`, which `pandas-gbq` uses.

If you know for certain you want to use their own accounts, we provide a [pydata_google_auth.get_user_credentials](https://pydata-google-auth.readthedocs.io/en/latest/api.html#pydata_google_auth.get_user_credentials) method. If you might sometimes want to use keys and/or gcloud SDK, then use the [pydata_google_auth.default](https://pydata-google-auth.readthedocs.io/en/latest/api.html#pydata_google_auth.default) method.

I have an example notebook here that used `pydata-google-auth` with the BigQuery Jupyter magics:

https://github.com/tswast/code-snippets/blob/main/2020/bigquery-python/user-credentials-magics.ipynb

**Comment by tswast** [comment]
Including the code samples here too for easier reference:

```python
# Install the google-cloud-bigquery and pydata-google-auth packages
# to use this code snippet.
import google.cloud.bigquery
import google.cloud.bigquery.magics
import pydata_google_auth
```


```python
# In the cell output, open the link to authenticate with your
# Google credentials.
credentials = pydata_google_auth.get_user_credentials(["https://www.googleapis.com/auth/cloud-platform"])
project_id = "my-project-id"
```


```python
# Configure the magics to use your credentials and project.
google.cloud.bigquery.magics.context.project = project_id
google.cloud.bigquery.magics.context.credentials = credentials
```


```python
%load_ext google.cloud.bigquery
```


```python
%%bigquery
SELECT name, SUM(number) as count
FROM `bigquery-public-data.usa_names.usa_1910_current`
GROUP BY name
ORDER BY count DESC
LIMIT 3
```


```python
# Configure a BigQuery client to use your credentials and project.
bqclient = google.cloud.bigquery.Client()
```


```python
query_job = bqclient.query(
"""SELECT name, SUM(number) as count
FROM `bigquery-public-data.usa_names.usa_1910_current`
GROUP BY name
ORDER BY count DESC
LIMIT 3
""")
query_job.result()
```


```python
query_job.to_dataframe()
```


```python

```

**Comment by tswast** [comment]
Hopefully this code sample resolves your issue. I'm hoping to make a sample like this more accessible at some point.

Let me know if this isn't what you meant.

**Comment by ianhellstrom** [comment]
Thanks!
