### ISSUE TITLE
use google-style docstrings

### ISSUE THREAD

**Issue by tswast** [googleapis/python-bigquery-pandas#391]
I notice in https://github.com/googleapis/python-bigquery-pandas/pull/389 that sphinx is able to render the numpy-style docstrings just fine even with the [`conf.py` from our shared templates](https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/python_library/docs/conf.py.j2). Still, it would be nice to use a similar style to our other libraries in `googleapis`.

**Comment by chalmerlowe** [comment]
Due to other priorities, closing this as Will Not Fix.
