### ISSUE TITLE
Supporting gcp workload identity federation?

### ISSUE THREAD

**Issue by ismailsimsek** [googleapis/python-bigquery-pandas#401]
Support gcp workload identity federation with this package ? 

https://cloud.google.com/iam/docs/workload-identity-federation

**Comment by tswast** [comment]
I haven't tried it, but presumably we do if you explicitly pass in a `credentials` object and/or set the credentials in [`pandas_gbq.context.credentials`](https://pandas-gbq.readthedocs.io/en/latest/api.html#pandas_gbq.context).

**Comment by ismailsimsek** [comment]
tested it with python and its working with identity federation. setting `GOOGLE_APPLICATION_CREDENTIALS` is enough.

Client libraries for Python support identity federation if they use version 1.27.0 or later of the google-auth package.
[google page ](https://cloud.google.com/iam/docs/using-workload-identity-federation#python)

```
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = json_credentials_path
credentials = google.auth.default()
```
