### ISSUE TITLE
read_gbq query keyword argument changed from 0.16.2 to 0.17.0

### ISSUE THREAD

**Issue by aafendi** [googleapis/python-bigquery-pandas#475]
#### Environment details

  - OS type and version: Databricks 9.1 LTS
  - Python version: 3.8.8
  - `pandas_gbq` version: 0.17.0

#### Steps to reproduce

Not a major problem, but the `read_gbq` function had its first keyword argument changed:
In 0.16.1 it was `query` and now in 0.17.0 it is `query_or_table`

**Comment by tswast** [comment]
Thanks for pointing this out. I hadn't realized folks were using `query` as a keyword argument.
