### ISSUE TITLE
Just showing love👍🏿

### ISSUE THREAD

**Issue by RichardMM** [googleapis/python-bigquery-pandas#558]
<img width="920" alt="image" src="https://user-images.githubusercontent.com/22428794/185464534-1b6a1fb8-ecf5-456b-9cab-4250f02677ab.png">
I appreciate this type of error messages that direct me to what I should do

**Comment by meredithslota** [comment]
Thank you! ❤️

**Comment by tswast** [comment]
I'm glad it was helpful! Note: in recent versions (after this PR https://github.com/googleapis/python-bigquery-pandas/pull/449/files#diff-425e6ca36042762d26859c069260f72610fe4f6efc8379e3a18a0fc7ee762cef) you can see the two schemas by inspecting the exception's `local_schema` and `remote_schema` properties.

https://github.com/googleapis/python-bigquery-pandas/issues/349 is still open to add relevant information (without properties at risk for containing PII) to the error message.
