### ISSUE TITLE
DATE converted to dbdate instead of datetime64[ns] dtype

### ISSUE THREAD

**Issue by ivan-toriya-precis** [googleapis/python-bigquery-pandas#579]
#### Environment details

  - OS type and version:
Env: `Google Colab`
OS type: `Linux-5.10.133+-x86_64-with-Ubuntu-18.04-bionic`
Version: `#1 SMP Fri Aug 26 08:44:51 UTC 2022`

  - Python version: `python --version`
`  Python 3.7.15`
  - pip version: `pip --version`
` pip 21.1.3 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)`
  - `pandas-gbq` version: `pip show pandas-gbq`
```
Name: pandas-gbq
Version: 0.17.9
Summary: Google BigQuery connector for pandas
Home-page: https://github.com/googleapis/python-bigquery-pandas
Author: pandas-gbq authors
Author-email: [googleapis-packages@google.com](mailto:googleapis-packages@google.com)
License: BSD-3-Clause
Location: /usr/local/lib/python3.7/dist-packages
Requires: db-dtypes, google-api-core, google-auth, google-auth-oauthlib, google-cloud-bigquery, google-cloud-bigquery-storage, numpy, pandas, pyarrow, pydata-google-auth, setuptools
Required-by:
```

#### Steps to reproduce

  1. Query any table with column DATE BigQuery type.
  2. Expect that the column will be converted to `datetime64[ns]` pandas dtype as said in the [docs](https://pandas-gbq.readthedocs.io/en/latest/reading.html#inferring-the-dataframe-s-dtypes).
  3. In reality it gets converted to `dbdate` type.

#### Code example

```python
import pandas_gbq
from google.colab import auth

auth.authenticate_user()

project_id = ""  # TODO: provide project ID

sql = f'''
  SELECT
    *
  FROM
    `bigquery-public-data.google_cloud_release_notes.release_notes`
  WHERE
    RAND() <= 0.1
'''

df = pandas_gbq.read_gbq(
    sql,
    project_id=project_id)

df.info()

```

```
Downloading: 100%|██████████| 1543/1543 [00:00<00:00, 3235.38rows/s]<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1543 entries, 0 to 1542
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   description           1543 non-null   object
 1   release_note_type     1543 non-null   object
 2   published_at          1543 non-null   dbdate
 3   product_id            1543 non-null   Int64 
 4   product_name          1543 non-null   object
 5   product_version_name  1091 non-null   object
dtypes: Int64(1), dbdate(1), object(4)
memory usage: 74.0+ KB
```

**Comment by tswast** [comment]
Thanks for the report. I think dbdate is the dtype we'll want for these columns. We should update the documentation.

**Comment by tswast** [comment]
Related: readthedocs is out-of-date https://github.com/googleapis/python-bigquery-pandas/issues/448

But https://googleapis.dev/python/pandas-gbq/latest/reading.html#inferring-the-dataframe-s-dtypes also needs an update.
