### ISSUE TITLE
PR #583 removed local_schema and remote_schema fields from InvalidSchema exception

### ISSUE THREAD

**Issue by ssuhre** [googleapis/python-bigquery-pandas#608]
#### Environment details

  - OS type and version: MacOS Ventura 13.1
  - Python version: 3.11.1
  - pip version: 22.3.1
  - `pandas-gbq` version: 0.19.0

PR #583 removes local_schema and remote_schema fields from InvalidSchema error. Was this by mistake? It was a very convenient feature to compare which column types mismatched

**Comment by chalmerlowe** [comment]
Closing as will not work.
