### ISSUE TITLE
The Conda-Forge channel is not updated with the 0.19.2 version

### ISSUE THREAD

**Issue by Bjarlex** [googleapis/python-bigquery-pandas#639]
#### Environment details

  - OS type and version:
  - Python version: `python 3.9`
  - pip version: `Conda 23.1.0`
  - `pandas-gbq` version: `0.19.1`

#### Steps to reproduce

  1. Go to Conda forge channel
  2. Look at latest version

**Comment by chalmerlowe** [comment]
Conda forge is now updated:

pandas-gbq 0.19.2

https://anaconda.org/conda-forge/pandas-gbq
