### ISSUE TITLE
BUG: read_gbq return timestamp as long int

### ISSUE THREAD

**Issue by itay-jether** [googleapis/python-bigquery-pandas#667]
Hey, I've tried to read parquet files using gbq, and it returns an integer instead of timestamps. example attached below
it works for me on python 3.10, same pandas and pandas_gbq version

#### Environment details

  - OS type and version: ubuntu 4.22
  - Python version: python 3.11.4
  - pip version:  22.3.1
  - `pandas-gbq` version: 0.19.2

#### Steps to reproduce
1. install python 3.11

#### Code example

```python
import pandas as pd


s = pd.Series(0, index=pd.date_range('2021-01-01 01', periods=24, freq='H', tz='UTC', name='ts')).to_frame().reset_index()
save_path = 'gs://my_bucket/test_dir'
s.to_parquet(f'{save_path}/test_gbq.parquet', index=False)
s_res = pd.read_gbq('select * from test_data', 
            configuration={'query': {
                'tableDefinitions': 
                    {'test_data': {'sourceFormat': 'PARQUET',
                                   'sourceUris': [f'{save_path}/*.parquet'],
                                   'autodetect': True}}}},
            location='eu'
)
print(s)
#                          ts  0
# 0 2021-01-01 01:00:00+00:00  0
# 1 2021-01-01 02:00:00+00:00  0
# 2 2021-01-01 03:00:00+00:00  0
# 3 2021-01-01 04:00:00+00:00  0
# 4 2021-01-01 05:00:00+00:00  0
print(s_res)
#                     ts  0
# 0  1609462800000000000  0
# 1  1609466400000000000  0
# 2  1609470000000000000  0
# 3  1609473600000000000  0
# 4  1609477200000000000  0

```

Thanks!

**Comment by itay-jether** [comment]
I see that it it's probably related to the new pyarrow version. 
I didn't notice that my 3.11 environment  is with pyarrow 13.0.0 and my 3.10 environment is with 12.0.1.
I'll leave open in case this is something that needs to be fixed here as well

**Comment by chalmerlowe** [comment]
thanks for this heads up.
were you able to discern the nature of the problem ... does the new version of pyarrow do some sort of behind the scenes conversion?

**Comment by itay-jether** [comment]
Unfortunately I didn't dive into the changes in Pyarrow, I just validated that this is the only change in my environment

**Comment by chalmerlowe** [comment]
Gonna be honest, I am struggling to get `pyarrow=13.0.0` with `Python 3.11` at all.
I am using the `mamba` resolver to evaluate package dependencies and it is not successfully resolving this. 

I was able to easily install `pyarrow=12.x` and that ran the code successfully, as expected.
This issue feels out of scope for my project and I think I need to close this issue for now as non-reproducible.
