### ISSUE TITLE
Provided Schema does not match Table, Cannot add fields  

### ISSUE THREAD

**Issue by almostintuitive** [googleapis/python-bigquery-pandas#691]
Hi! We're trying to add new columns while calling `to_gbq()` dynamically, but it fails as I assume it's trying to create a required field /column rather than a nullable one. Is this expected / are there any ways we could override it to create nullable columns when it's modifying an existing Schema?

Thank you!

**Comment by Linchin** [comment]
Hi @almostintuitive, thank you for reporting the issue. Could please provide a minimum code snippet that can reproduce the error, as well as the error tracing? It would be very helpful for me to reproduce the issue.

**Comment by almostintuitive** [comment]
Sorry, I think the library didn't intend to support our usecase. we've created a private fork and implemented this functionality.
