### ISSUE TITLE
conda test failing with python 3.12

### ISSUE THREAD

**Issue by Linchin** [googleapis/python-bigquery-pandas#708]
error log: https://btx-internal.corp.google.com/invocations/5b5865bc-cc72-459b-8183-83ceb1a26d1e/targets

The dependencies resolved with conda is very old, compared to the former results in python 3.11, such as [this one](https://fusion2.corp.google.com/invocations/6b26cb6c-19c8-4914-98df-7327d0f5bbe0/targets).

This error arises when running test for the python 3.12 support (#702).

**Comment by tswast** [comment]
> The dependencies resolved with conda is very old

Would you mind sharing which dependencies in particular need updating, please?

**Comment by Linchin** [comment]
Hi @tswast, here's a copy from the error log: https://gist.github.com/Linchin/3e9b172f7f8b976f5bc2a9bcad0adfc2

For example, google-cloud-bigquery is resolved to be v3.4.1, with the current version at v3.14.1.

**Comment by chalmerlowe** [comment]
Per results in Test Fusion, there does not appear to be any issues with version 3.12.
