### ISSUE TITLE
python

### ISSUE THREAD

**Issue by Millena-DEV** [googleapis/python-bigquery-pandas#799]
estou com esse erro aparecendo alguem pode me ajudar 
 The conflict is caused by:
    basedosdados 1.6.1 depends on google-cloud-bigquery==2.30.1

**Comment by Linchin** [comment]
Hi @Millena-DEV, thanks for opening the issue. From the error message it looks like a version conflict in your dependencies, so I suggest you look into that. I don't think this is an issue with this code base, so I will close this issue now. If you have further questions, feel free to leave a comment below :)
