### ISSUE TITLE
String Columns Not Filling Null Value Into BQ - Passing Stringified Value Instead

### ISSUE THREAD

**Issue by HgCNO2** [googleapis/python-bigquery-pandas#802]
I have a script that pulls down a report from an API and puts it into a dataframe. The dataframe in my example has the following columns with the mapped dtypes:

```
date                    datetime64[ns]
id                              object
program                         object
raw_clicks                       int32
clicks                           int32
actions                          int32
sales                            int32
sale_amount                    float64
sale_earnings                  float64
sale_conversion_rate           float64
sale_reversal_rate             float64
sale_epa                       float64
sale_epc                       float64
```

The table in BQ has no default values and all fields are nullable. However, when the value for `id` is `None`, `pd.NA`, `np.nan`, or even (as a last-ditch effort) "", or "Null", the rows inserted use the string value representation of these. For example, in respective order, "None", "<NA>", "nan", "", and "Null". None of the values actually come in as _null_.

I'm wondering if it's something to do with Python handling string columns as objects? Makes me think this could be a bug with a feature opportunity, to include a function parameter of `null_value` which can take a string or list-like value that converts them to null when passing to BQ on `pandas_gbq.to_gbq()`.

#### Environment details

  - OS type and version:
  - Python version: 3.11.2
  - pip version: 24.2
  - `pandas-gbq` version: 0.23.1

#### Steps to reproduce

  1. Have an existing example table in BQ that includes a nullable string column.
  2. Create a dummy dataframe with columns that match the BQ table where at least one row has a value of `None`, `pd.NA`, `np.nan`, etc. and push that dataframe into BQ using `pandas_gbq.to_gbq()`.
  3. Query or preview the table to see how those new rows were imported. 

#### Code example

```python
# Creating the data
data = {
    "A": ["fibonacci", None, pd.NA, np.nan, "", "Null", "Testing"],
    "B": [1, 2, 3, 5, 8, 13, 21]
}

# Creating the DataFrame
df = pd.DataFrame(data)

# Push to BQ
pandas_gbq.to_gbq(df, "project_name.dataset_name.example_table", if_exists="append", credentials=credentials)
```

**Comment by HgCNO2** [comment]
My workaround in the meantime is to send all `NULL` values as a specific value - probably `None` - then have a scheduled query to update all values in that column to `NULL` where the column equals that value.

```sql
UPDATE project_name.dataset_name.example_table
SET "A" = NULL
WHERE "A" = "None"
```

**Comment by Shashank0309-hub** [comment]
The problem with this issue what i think is to_gbq() function is mostly for pushing the data to bq instead of transforming the data inside the function. According to me, it would be better if you transform string null values to none before calling the to_gbq() function

**Comment by HgCNO2** [comment]
Indeed it is. The problem is when you have a `None` value, it populates into BigQuery as the string "None" rather than `NULL`. 

I thought my example code indicated that the DataFrame already has a variety of missing-type data. This problem is not unique to `None`, but also happens with `pd.NA` and `np.nan`, both of which are also used to indicate missing values and should appear in BigQuery as `NULL`

**Comment by Shashank0309-hub** [comment]
I tested the code with these values and on bq these all values are coming as null

Can you once confirm am I going in the right direction or not?

![image](https://github.com/user-attachments/assets/7b60ba97-b32f-4625-ab20-ffd78b2493c4)

**Comment by HgCNO2** [comment]
What version are you on? I just tested my example code to create a completely new table and `None`, `pd.NA`, and `np.nan` all came through as `NULL` but the strings came through as strings. Then I ran it again to append another set.

![image](https://github.com/user-attachments/assets/4bf464f7-a377-4bb1-a103-a74f76664a20)

The fact that your strings are also getting converted to `NULL` makes this seem like a larger problem of inconsistencies when data is being pushed in.

I definitely have a table that I can't really share details about that has the problem I described in the original post. Basically I'm pulling a report from an API and it returns blank rows as empty strings, ie "". So I'm using `df[col_name].replace("", None, inplace=True)` to make all empty strings into `None`. And when that gets pushed into the existing table I have in BQ, they come through as "None"

**Comment by Shashank0309-hub** [comment]
As i mentioned, the strings which are having none or null that i converted to null before throwing to bq for testing purpose

`pandas-gbq` version: 0.23.1

I used your same code to convert "" to None and then push it and as you can see its coming as None 

![image](https://github.com/user-attachments/assets/11caa18b-1529-4c44-8791-c9f8f219db2b)

![image](https://github.com/user-attachments/assets/7a258ded-72a0-4585-96f3-32db5013245a)

**Comment by HgCNO2** [comment]
I wonder why it's failing to do that with my real-world DataFrame and table.

**Comment by Shashank0309-hub** [comment]
Can you once try debugging of data frame just before pushing the it to to_gbq ?

**Comment by HgCNO2** [comment]
This might be a dumb question, but what exactly do you mean debugging the data frame just before pushing it? What am I looking for specifically?

**Comment by Shashank0309-hub** [comment]
i mean just before throwing the data in to_gbq() function just export the data and check the data once

**Comment by HgCNO2** [comment]
Oh god, I'm an idiot. I had the code in this order:

```python
...
final_report['id'].replace("", None, inplace=True)
...
final_report = final_report.astype({
        "id": str,
        "raw_clicks": int,
        "clicks": int,
        ...
    })
```

That, obviously, converts `None` into `"None"`.

Problem resolved. Thanks for the help.

**Comment by Shashank0309-hub** [comment]
Glad you got the issue
