### ISSUE TITLE
If a column name contains a dash, `to_gbq` writes its values as nulls

### ISSUE THREAD

**Issue by jamesdunham** [googleapis/python-bigquery-pandas#812]
I ran into a possible issue loading data into BQ.

#### Environment details

  - OS type and version: MacOS Sonoma 14.6.1 
  - Python version: 3.11.9
  - pip version: 24.2
  - `pandas-gbq` version: 0.23.1; `arrow`: 1.3.0; `pyarrow`: 15.0.2; `pyarrow-hotfix`: 0.6

#### Steps to reproduce

  1. Create a DataFrame with a column whose name contains a dash, like `2020-2021`. (Other columns whose names need to be escaped in BQ, like `2022`, are unaffected.)
  2. Load the table using `to_gbq`. It'll appear successful, but the values in (just) the dash-named column will be null.

#### Code example

```python
import pandas as pd
import pandas_gbq as gbq

df = pd.DataFrame({'2020-2021': [1, 2], '2022': [3, 4]})
df.head()

#   2020-2021  2022
#0          1     3
#1          2     4

gbq.to_gbq(df, 'sandbox.temp', if_exists='replace')
# 100%|██████████| 1/1 [00:00<00:00, 5949.37it/s]

# confirmed with `bq show` and in the console
gbq.read_gbq('sandbox.temp')
#   2020-2021  2022
#0       <NA>     3
#1       <NA>     4
```

I tried replicating this using bigframes.pandas but couldn't, so the easiest workaround for me when dealing with column names like this -- when it isn't possible to avoid them -- is to load like:

```python
import bigframes.pandas as bfp

df = pd.DataFrame({'2020-2021': [1, 2], '2022': [3, 4]})
bfp.DataFrame(df).to_gbq('sandbox.temp', if_exists='replace')

# confirm
gbq.read_gbq('sandbox.temp')
# Downloading: 100%|██████████|
#   2020-2021  2022
#0          2     4
#1          1     3

```

HTH and thanks for all your work on the library.

**Comment by jamesdunham** [comment]
Ah I didn't catch this when searching: seems like another case of #779.

**Comment by chalmerlowe** [comment]
@jamesdunham 

Following up on this.
I know that just recently, flexible column names went Generally Available (GA) in BigQuery (BQ). [Blog post from September 14th](https://cloud.google.com/blog/products/data-analytics/new-bigquery-sql-capabilities-on-tap).

I ran some tests on my project to see if I can create column names with hyphens as well as try to create a column name with a foreign character. Both situations worked as expected. 

```
In [1]: import pandas_gbq as gbq
In [2]: import pandas as pd
In [3]: df = pd.DataFrame({'2020-2021': [1, 2], '2022': [3, 4]})

In [4]: df.head()
Out[4]: 
   2020-2021  2022
0          1     3
1          2     4

In [6]: gbq.to_gbq(df, 'my_project.experimental.temp', if_exists='replace')
100%|█████████████████| 1/1 [00:00<00:00, 23967.45it/s]

In [7]: gbq.read_gbq('my_project.experimental.temp')
Downloading: 100%|██████████████████████|
Out[7]: 
   2020-2021  2022
0          1     3
1          2     4

In [8]: df_foreign = pd.DataFrame({'2020-2021-列': [1, 2], '2022': [3, 4]})

In [9]: gbq.to_gbq(df_foreign, 'my_project.experimental.temp_foreign', if_exists='replace')
100%|████████████████| 1/1 [00:00<00:00, 28728.11it/s]

In [10]: gbq.read_gbq('my_project.experimental.temp_foreign')
Downloading: 100%|█████████████████|
Out[10]: 
   2020-2021-列  2022
0            1     3
1            2     4
```

**Comment by chalmerlowe** [comment]
Closing per the above comment.

**Comment by StankovskiA** [comment]
@chalmerlowe I am having the same issues with the dashes. I've been using the pandas-gbq 0.23.2 version

**Comment by chalmerlowe** [comment]
Not sure what to tell you, without more information about your setup.
I would take a [look here for some guidelines, configurations, and limitations](https://cloud.google.com/bigquery/docs/schemas#flexible-column-names) on the use of Flexible Column Names.

Namely:
* if used with the Bigquery Storage Read API, we need to set a configuration flag.
* if used with the BigQuery Storage Write API we need to provide a column name as part of the schema.

There are also limitations on using flexible names with external tables.
